#4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
##Problem - 1: Array Creation:

###1. Initialize an empty array with size 2X2.


In [ ]:
import numpy as np
empty_array = np.zeros((2, 2))
empty_array


array([[0., 0.],
       [0., 0.]])

###2. Initialize an all one array with size 4X2.

In [ ]:
a=np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

###3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
a = np.full((3, 3), 9)
a

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

###4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
b=np.zeros_like(a)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

###Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
b=np.ones_like(b)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list=[1,2,3,4]
new_array=np.array(new_list)
new_array

array([1, 2, 3, 4])

##Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

###1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [ ]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

###Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array=np.random.random(30)
mean_value=random_array.mean()
mean_value

np.float64(0.4142800553736468)

###5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_array=np.random.random((10,10))
min_value=random_array.min()
max_value=random_array.max()
#print(random_array)
print("minimum:" ,min_value)
print("maximum:" ,max_value)

minimum: 1.8036345718952518e-05
maximum: 0.9993325986565251


###6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr=[1,2,0,0,4,0]
reversed_arr=arr[::-1]
reversed_arr

[0, 4, 0, 0, 2, 1]

###8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
def create_bordered_array(rows, cols):
    arr = np.ones((rows, cols))
    if rows > 2 and cols > 2:
        arr[1:-1, 1:-1] = 0
    return arr
bordered_array = create_bordered_array(5, 5)
bordered_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [8]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

addition=x+y
print("1.addiditon:\n",addition)

subtraction=x-y
print("2.subtraction:\n",subtraction)

multiplication=x*2
print("3.multiplication:\n",multiplication)

x_squared = x ** 2
y_squared = y ** 2
print("4. x^2 =\n", x_squared)
print("   y^2 =\n", y_squared)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("5. Dot products:")
print("   v · w =", dot_vw)
print("   x · v =", dot_xv)
print("   x · y =\n", dot_xy)

concat_rows = np.concatenate((x, y), axis=0)
print("6a. Concatenate x and y along rows:\n", concat_rows)

# Reshape to column vectors (2,1)
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)

concat_cols = np.concatenate((v_col, w_col), axis=1)
print("6b. Concatenate v and w along columns:\n", concat_cols)

try:
    bad_concat = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("7. Error when concatenating x and v:", e)

1.addiditon:
 [[ 6  8]
 [10 13]]
2.subtraction:
 [[-4 -4]
 [-4 -3]]
3.multiplication:
 [[ 2  4]
 [ 6 10]]
4. x^2 =
 [[ 1  4]
 [ 9 25]]
   y^2 =
 [[25 36]
 [49 64]]
5. Dot products:
   v · w = 219
   x · v = [29 77]
   x · y =
 [[19 22]
 [50 58]]
6a. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]
7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [14]:
A = np.array([[3, 4],
              [7, 8]],dtype=float)

B = np.array([[5, 3],
              [2, 1]],dtype=float)

A_inv = np.linalg.inv(A)
AA_inv = np.dot(A, A_inv)
I = np.eye(2)

print("1. A @ A⁻¹ =\n", AA_inv)
print("Identity matrix I =\n", I)
print("Is A @ A⁻¹ ≈ I?", np.allclose(AA_inv, I))

AB = np.dot(A, B)
BA = np.dot(B, A)

print("\n2. AB =\n", AB)
print("   BA =\n", BA)
print("   AB == BA?", np.array_equal(AB, BA))

AB = np.dot(A, B)
AB_T = AB.T

BT_AT = np.dot(B.T, A.T)

print("\n3. (AB)^T =\n", AB_T)
print("   B^T A^T =\n", BT_AT)
print("   (AB)^T == B^T A^T?", np.allclose(AB_T, BT_AT))

A_sys = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]], dtype=float)

C = np.array([-1, -3, 9], dtype=float)

A_inv_sys = np.linalg.inv(A_sys)
X = np.dot(A_inv_sys, C)

print("\nSolution using inverse method:")
print(f"x = {X[0]:.4f}, y = {X[1]:.4f}, z = {X[2]:.4f}")

1. A @ A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I =
 [[1. 0.]
 [0. 1.]]
Is A @ A⁻¹ ≈ I? True

2. AB =
 [[23. 13.]
 [51. 29.]]
   BA =
 [[36. 44.]
 [13. 16.]]
   AB == BA? False

3. (AB)^T =
 [[23. 51.]
 [13. 29.]]
   B^T A^T =
 [[23. 51.]
 [13. 29.]]
   (AB)^T == B^T A^T? True

Solution using inverse method:
x = 2.0000, y = 1.0000, z = -2.0000
